# Generated by Django 5.2 on 2025-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='user',
            new_name='User',
        ),
        migrations.AddField(
            model_name='tasks',
            name='Completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
