# Generated by Django 5.2 on 2025-04-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_rename_status_tasks_status_rename_user_tasks_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
